name: Sync DAGs Git

on:
  workflow_run:
    workflows:
      - 'Test DAGs'
    types:
      - completed
  pull_request:
    types:
      - closed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Pushes to another repository
        uses: lazkamal/aiflow_dags@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dags'
          destination-repository-username: 'lazkamal'
          destination-repository-name: 'DAGS_VALIDATION'
          user-email: lazkamal34@gmail.com
          target-branch: main
